name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    environment: docker
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v3
    - name: prepare
      run: ln -s Makefile.Linux Makefile
    - name: build
      run: make
    - name: docker-login
      uses: docker/login-action@v2.1.0
      with:
        # Username used to log against the Docker registry
        username: '${{ secrets.DOCKER_USERNAME }}'
        # Password or personal access token used to log against the Docker registry
        password: '${{ secrets.DOCKER_PASSWORD }}'
    - name: docker-build
      run: docker build -f Dockerfile.full -t truegameover/3proxy .
    - name: docker-push
      run: docker push truegameover/3proxy:latest
